name: rick_and_morty_characters
description: "Rick and Morty characters list with favorites and offline cache."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # UI
  shimmer: ^3.0.0

  # Utils
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0

  # Local services
  shared_preferences: ^2.5.4
  cached_network_image: ^3.4.1

  # Remote services
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
